version: '3.4'

services:
  db:
    container_name: banners-rotation-storage
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: banner
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./.docker/data/storage:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  rabbit:
    image: rabbitmq:3.9.11-management
    container_name: banners-rotation-rmq
    ports:
      - "5672:5672"
      - "15672:15672"

  app:
    container_name: banners-rotation-app
    build:
      context: ./
      dockerfile: dockerfile
    restart: always
    depends_on:
      - db
      - rabbit
    ports:
      - "8080:8080"
